config/routes.rb
Rails.application.routes.draw do
  
  get 'users/index'
  get 'users/show'
  devise_for :users
  root 'questions#index'
  
  resources :questions do
    resources :answers
    
  end
  resources :topics do
    collection do
      post :follow
      post :unfollow
    end
  end
  
  resources :users do
    collection do
      post :follow
      post :unfollow
    end
    get :followers
    get :followings
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
    belongs_to :follower, :class_name => "User"
    belongs_to :following, :class_name => "User"

    validates :follower_id, uniqueness: { scope: :following_id }

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, allow_destroy: true
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/topic_follower.rb
class TopicFollower < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  validates :user_id, uniqueness: { scope: :topic_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :follower_users, :class_name => "Follower", :foreign_key => "following_id"
  has_many :following_users, :class_name => "Follower", :foreign_key => "follower_id"

  has_many :followers, through: :follower_users, class_name: "User", foreign_key: "follower_id"
  has_many :followings, through: :following_users, class_name: "User", foreign_key: "following_id"

  has_many :questions
  has_many :answers
  has_many :topics
  has_many :topic_followers


  def is_following?(user)
    followings.where(id: user.id).any?
  end

  def is_following_topic?(topic)
    topic_followers.where(topic_id: topic.id).any?
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def new
  end

  def edit
  end

  def index
  end


  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      if params[:answer][:from] == 'view'
        redirect_to @answer.question
      else
        redirect_to questions_path
      end
    else
      render :new
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.destroy
    redirect_to params[:from] == 'view' ? question_path(@question) : questions_path
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.update(answer_params)
    redirect_to @question
  end

  private

  def answer_params
    params.require(:answer).permit(:answer, :question_id, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find params[:id]
  end

  def show 
    @question = Question.find params[:id]    
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def update
    @question = Question.find params[:id]
    if @question.update(question_params)
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:question, :user_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.find params[:id]
  end

  def update
    @topic = Topic.find params[:id]
    @topic.update(topic_params)
    redirect_to topics_path
  end

  def index
    @topics = Topic.all
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to topics_path
    else
      render :new
    end
  end

  def follow
    TopicFollower.create(user_id: params[:user_id], topic_id: params[:topic_id])
    redirect_to topics_path
  end

  def unfollow
    TopicFollower.find_by(user_id: params[:user_id], topic_id: params[:topic_id]).destroy
    redirect_to topics_path

  end
  private

  def topic_params
    params.require(:topic).permit(:name, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @users = User.all
  end


  def show
    @user  = User.find params[:id]
  end

  def follow
    @follower = Follower.new(follower_id: params[:follower_id], following_id: params[:following_id])
    if @follower.save
      redirect_to user_path(params[:following_id])
    end
  end

  def unfollow
    @follower = Follower.find_by(follower_id: params[:follower_id], following_id: params[:following_id])
    if @follower.destroy
      redirect_to user_path(params[:following_id])  
    end
  end

  def followers
    @user = User.find_by(id: params[:user_id])
    @followers = @user.followers
  end

  def followings
    @user = User.find_by(id: params[:user_id])
    @followings = @user.followings
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/edit.html.erb
<h1>Answers#edit</h1>
<p>Find me in app/views/answers/edit.html.erb</p>

app/views/answers/index.html.erb
<h1>Answers#index</h1>
<p>Find me in app/views/answers/index.html.erb</p>

app/views/answers/new.html.erb
<h1>Answers#new</h1>
<p>Find me in app/views/answers/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quara</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Home", root_path%>
  <div class="session">
    <% if user_signed_in? %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>  
      </li>
      <li>
        <%= link_to current_user.email, user_path(current_user)%>     

      </li>
      <% else %>
      <li>
      <%= link_to('Login', new_user_session_path) %>  
      </li>
   
    <% end %>
  </div>
  <hr/>
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f|%>
    <%= f.label :question%>
    <%= f.text_area :question%>
    <%= f.hidden_field :user_id, value: current_user.id%>

    <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h3> Update Question </h3>

<%= render 'form'%>

app/views/questions/index.html.erb
<%= link_to "Follow Users", users_path %>
<%= link_to "Follow Topics", topics_path, class: 'm-l-10' %>
<hr/>
<%= link_to "Add Question", new_question_path, class: 'm-l-10'%>
</br>

<h3> Questions </h3>
<hr/>
<% @questions.all.each do |question|%>
  </br>
  <span class='m-b-10'>

    <strong><%=question.question%></strong>

    &nbsp; <%= link_to "View", question_path(question)%>
  </span>
  </br> 
  By <%= link_to question.user.email, user_path(question.user)%>
  At <%= question.created_at.strftime("%d/%m/%y - %H:%M:%S")%>
  <h5> Answers  (<%= question.answers.count %>) </h5>
  <% question.answers.each do |answer|%>
    <%= answer.answer %>
     By 
    <%= link_to answer.user == current_user ? "You" : answer.user.email, user_path(answer.user)%>
    &nbsp;
    At : <%= answer.created_at.strftime("%d/%m/%y - %H:%M:%S") %>
    <%if current_user && answer.user == current_user%>
      </br>
      <div class='remove'>
        <%= link_to "Remove", question_answer_path(question, answer), method: :delete%>
      </div>
    <%end%>
    </br>
    </br>
  
  <%end%>
  <%if current_user %>
    <h5> Add your answer</h5>
    <%= form_for [question, question.answers.build] do |ans|%>
      <%= ans.text_field :answer%>
      <%= ans.hidden_field :user_id, value: current_user.id%>
      <%= ans.hidden_field :question_id, value: question.id%>

      <%= ans.submit "Save"%>
    <% end%>
  <%end%>
  <hr/>

<%end%>

app/views/questions/new.html.erb
<h3> New Question </h3>

<%= render 'form'%>

app/views/questions/show.html.erb
</br>
  <strong>
    <%=@question.question%>
    <%if current_user == @question.user%>
      &nbsp;
      <%= link_to "Edit", edit_question_path(@question) %>
 
      &nbsp;
      <%= link_to "Remove", question_path(@question), method: :delete  %>
    <% end %>
  </strong>
  </br>
  created by <%= link_to @question.user == current_user ? "You" : @question.user.email, user_path(@question.user)%>

  <h5> Answers  (<%= @question.answers.count %>)</h5>
  <% @question.answers.each do |answer|%>
    <div class="answer">
      <div class='answer-detail'>
        <%= answer.answer %> </br>
        <span class='m-l-5'>
          By 
          <%= link_to answer.user == current_user ? "You" : answer.user.email, user_path(answer.user)%>
          at : <%= answer.created_at.strftime("%d/%m/%y - %H:%M:%S") %>
        </span>
          <%if current_user && answer.user == current_user%>
          </br>
          <%= link_to "Edit", "javascript:void(0)", class: 'edit-answer'%>

          <%= link_to "Remove", question_answer_path(@question, answer, from: 'view'), method: :delete %>
        <%end%>
        </br></br>
      </div>
      <div class='answer-edit-form hide'>
        <%= form_for [@question, answer] do |f|%>
          <%= f.text_area :answer %>
          <%= hidden_field_tag :from, 'question' %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>

  <%end%>
  
  <h5> Add your answer</h5>
  <%= form_for [@question, @question.answers.build] do |ans| %>
    <%= ans.text_field :answer%>
    <%= ans.hidden_field :user_id, value: current_user.id %>
    <%= ans.hidden_field :question_id, value: @question.id %>
    <%= ans.hidden_field :from, value: 'view' %>
    <%= ans.submit "Save" %>
  <% end %>
  <hr/>

  <%= link_to "Back", questions_path %>

<script>
    $(document).on('ready', function(){
      $('.edit-answer').on('click', function(){
        $(this).parent('.answer-detail').siblings('.answer-edit-form').removeClass('hide');
        $(this).parent('.answer-detail').addClass('hide');
      })
    })
</script>

app/views/topics/_form.html.erb
<%= form_for @topic do |f|%>
    <%= f.label :name%>
    <%= f.text_field :name %>
    <%= f.hidden_field :user_id, value: current_user.id %>  
    <%= f.submit%>  
<%end%>

app/views/topics/edit.html.erb
<h3> Edit Topic </h3>
<%= render "form"%>

app/views/topics/index.html.erb
<%= link_to "Add Topic", new_topic_path%>
<h3>List of Topics </h3>
<hr/>
<% @topics.each do |topic| %>
  <strong><%= topic.name%> </strong>
      <%if current_user.is_following_topic?(topic)%>
        <%= link_to "Un Follow", unfollow_topics_path(user_id: current_user.id, topic_id: topic.id), method: :post %>
      <%else%>
        <%= link_to "Follow", follow_topics_path(user_id: current_user.id, topic_id: topic.id), method: :post %>      
      <%end%>
  <br/>
  <br/>
<% end %>
<hr/>
<%= link_to "Back", root_path%>

app/views/topics/new.html.erb
<h3> New Topic </h3>
<%= render "form"%>

app/views/users/followers.html.erb
<h3>List of Followers </h3>

<% @followers.each do |user|%>

    <%= link_to user.email, user_path(user)%>

<br/>
<%end%>

<br/>
<br/>


<%= link_to "Back", user_path(@user) %>

app/views/users/followings.html.erb
<h3>List of Followings </h3>

<% @followings.each do |user|%>

    <%= link_to user.email, user_path(user)%>
    <br/>

<%end%>
<br/>
<br/>

<%= link_to "Back", user_path(@user) %>

app/views/users/index.html.erb
<h3>List of Users </h3>
<% @users.each do |user| %>
  <%= user.email%>
    <% if current_user != user %>
      <%if current_user.is_following?(user)%>
        <%= link_to "Un Follow", unfollow_users_path(following_id: user.id, follower_id: current_user.id), method: :post %>
      <%else%>
        <%= link_to "Follow", follow_users_path(following_id: user.id, follower_id: current_user.id), method: :post %>      
      <%end%>
    <%end%>
  
  <br/>
  <br/>
<% end %>

<%= link_to "Back", root_path%>

app/views/users/show.html.erb
<h2> Profile </h2>
<h3> 
  <%= @user.email%> 
  <%if @user!= current_user%>
      <%if current_user.is_following?(@user)%>
          <%= link_to "Un Follow", unfollow_users_path(following_id: @user.id, follower_id: current_user.id), method: :post %>
      <%else%>
          <%= link_to "Follow", follow_users_path(following_id: @user.id, follower_id: current_user.id), method: :post %>      
      <%end%>
      <br/>
  <%end%>
</h3>
<br>
<%= link_to "Followers (#{@user.followers.count})", user_followers_path(@user)%>
&nbsp;&nbsp;&nbsp;
<%= link_to "Followings (#{@user.followings.count})", user_followings_path(@user)%>
<hr>
<h4> Questions of users (<%= @user.questions.count %>) <h4>

<% @user.questions.each do |q|%>
    <%=link_to q.question, question_path(q)%>
    <br>
    <br>
<%end%>

<hr/>

<h4> Answers of users  (<%= @user.answers.count %>) <h4>

<% @user.answers.each do |a|%>
  Que.  <%= link_to a.question.question, question_path(a.question) %>
    <br/>
  Ans. <%= a.answer%>
  <br/>
  <br/>
<%end%>

<hr/>

<h4> Topics followed by users (<%= @user.topic_followers.count %>) <h4>

<% @user.topic_followers.each do |follow|%>
    <%=  follow.topic.name %>
    <br/>
  <br/>
<%end%>